In [3]:
from numpy import *
a = arange(15).reshape(3,5)
a.itemsize

8

In [7]:
one = ones((2,3,4),dtype=int16) 
one.shape

(2, 3, 4)

In [9]:
ar = arange(10,30,5)
ar

array([10, 15, 20, 25])

In [12]:
def f(x,y):
    return 10*x+y
b = fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [14]:
b1 = b[:4:3] - 100
b1

array([[-100,  -99,  -98,  -97],
       [ -70,  -69,  -68,  -67]])

In [16]:
c = array( [ [[  0,  1,  2], [ 10, 12, 13]]])
c[:,:,2]

array([[ 2, 13]])